### ISSUE TITLE
Hot Key?

### ISSUE THREAD

**Issue by sliceofbytes** [srilakshmikanthanp/QuickNote#10]
Am I missing some settings or anything. Is their a hot key to open it at cursor etc? Where is the file saved when you save the note?

**Comment by srilakshmikanthanp** [comment]
Hey, Thanks for reaching out,

1) Currently there are no hotkeys simply press the icon at the task bar to open quicknote.
2) The file saved in `C:\Users\<username>\.quicknote directory` 

Note: the file is not supposed to be read by a human since It has some style info (managed by Facebook's lexical)

**Comment by srilakshmikanthanp** [comment]
As with commit, ab7133afe552377e51af1df1c5a9ea68b31a6f84 Added a Hot key as `CTRL + ALT + Q` to open at the position of the cursor, The changes will reflect in the next version :)
